#!/usr/bin/env python3
"""Export the literature record table and the cache of best packings as ES modules for web/."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import numpy as np  # noqa: E402

from squarepack.geometry import verify  # noqa: E402
from squarepack.known import RECORDS  # noqa: E402


def main():
    out = ROOT / "web" / "js"
    out.mkdir(parents=True, exist_ok=True)
    recs = sorted((int(n), float(s), ex, note) for n, (s, ex, note) in RECORDS.items())
    lines = ["// generated by scripts/export_web.py from squarepack/known.py (Friedman / Ellsworth record table)",
             "export const RECORDS = [", *[f"  [{n}, {s!r}, {json.dumps(ex)}, {json.dumps(note[:80])}]," for n, s, ex, note in recs], "];",
             "export const RECORD_MAX_N = 324;",
             "/** best known side for n (min over listed m >= n), or null beyond the table */",
             "export function bestKnown(n) {",
             "  if (n < 1 || n > RECORD_MAX_N) return null;",
             "  let best = Math.ceil(Math.sqrt(n) - 1e-12);",
             "  for (const [m, s] of RECORDS) if (m >= n && s < best) best = s;",
             "  return best;",
             "}",
             "export function recordEntry(n) {",
             "  const b = bestKnown(n); if (b === null) return null;",
             "  for (const r of RECORDS) if (r[0] >= n && Math.abs(r[1] - b) < 1e-12) return {n: r[0], s: r[1], exact: r[2], note: r[3]};",
             "  return {n, s: b, exact: String(b), note: 'trivial grid'};",
             "}"]
    (out / "records.js").write_text("\n".join(lines) + "\n")
    cache_file = ROOT / "data" / "best_packings.json"
    entries = []
    if cache_file.exists():
        raw = json.loads(cache_file.read_text())
        for key, ent in sorted(raw.items(), key=lambda kv: int(kv[0])):
            n = int(key)
            sq = np.asarray(ent["squares"], float).reshape(-1, 3)
            if len(sq) == n and verify(ent["s"], sq, 1e-9).ok:
                flat = ",".join(f"{v:.13g}" for v in sq.ravel())
                entries.append(f"  {n}: {{s: {ent['s']!r}, method: {json.dumps(ent.get('method', ''))}, exact: {json.dumps(ent.get('exact', ''))}, squares: [{flat}]}},")
    (out / "cache.js").write_text("// generated by scripts/export_web.py from data/best_packings.json (verified on export)\n"
                                  "export const CACHE = {\n" + "\n".join(entries) + "\n};\n")
    print(f"records: {len(recs)}, cached packings: {len(entries)}")


if __name__ == "__main__":
    main()
